version: "3"
services:
  gravity-sdoh-cp:
    build: .
    container_name: gravity-sdoh-cp
    restart: on-failure
    ports:
      - "8080:8080"
  gravity-sdoh-cp-postgres:
    image: postgres:13-alpine
    container_name: gravity-sdoh-cp-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - gravity-sdoh-cp-postgres:/var/lib/postgresql/data
volumes:
  gravity-sdoh-cp-postgres:
