version: "3"
services:
  gravity-sdoh-cp:
    build: .
    container_name: gravity-sdoh-cp
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://gravity-sdoh-cp-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
    ports:
      - "8082:8080"
  gravity-sdoh-cp-postgres:
    image: postgres:15-alpine
    container_name: gravity-sdoh-cp-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - gravity-sdoh-cp-postgres:/var/lib/postgresql/data
volumes:
  gravity-sdoh-cp-postgres:
